name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'CODE_OF_CONDUCT.md'
      - '.editorconfig'
      - '.spi.yml'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: macOS-14
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.1.app/Contents/Developer
    strategy:
      matrix:
        destination:
          - "platform=macOS"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Test platform ${{ matrix.destination }}
        run: set -o pipefail && xcodebuild -scheme ThemePark -destination "${{ matrix.destination }}" test
